static-resource:
  paths:
    '[/**]':
      - classpath:/
      - classpath:/premier-lineup-ui/
      - classpath:/public/
      - classpath:/static/
      - file:///c:/upload-dir/
    '[/assets]':
      - file:///c:/upload-dir/
