server:
  servlet:
    encoding:
      force-response: true
spring:
  profiles:
#    include: resources, store, production, develop
    include: resources, store, production, product
  servlet:
    multipart:
      max-file-size: 2048KB
      max-request-size: 2048KB
  resources:
    cache: false
    cache.period: 0
  template:
    cache: false
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  datasource:
    jpa:
#      database-platform: org.hibernate.dialect.OracleDialect -- no
#      database-platform: org.hibernate.dialect.Oracle9iDialect -- no
#      database-platform: org.hibernate.dialect.Oracle10gDialect -- yes
#      database-platform: org.hibernate.dialect.H2Dialect
      database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      springframework:
        security: DEBUG
    root: INFO
    com.rh: INFO
  pattern:
    file: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
  file:
    path: ./application.log
database:
  packages-to-scan:
    - ir.piana.business.premierlineup.common.data.entity
    - ir.piana.business.premierlineup.module.**.data.entity
#spirit detect tobacco pink access drum blind quit forest knee pig camp
