server:
  servlet:
    encoding:
      force-response: true
spring:
#  profiles:
#    include: resources, store, production, product
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:mem:support
      username: support
      password: s
      driverClassName: org.h2.Driver
  servlet:
    multipart:
      max-file-size: 2048KB
      max-request-size: 2048KB
  resources:
    cache: false
    cache.period: 0
  template:
    cache: false
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  datasource:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
#      database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      springframework:
        security: DEBUG
    root: INFO
    com.rh: INFO
  pattern:
    file: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
  file:
    path: ./application.log
