GET https://piana.ir:8443/api/modules/general/menu/test
tenant: 10743
#tenant: 11517
#tenant: support

###
GET https://piana.ir:8443/api/modules/general/menu

###
GET https://piana.ir:8443/api/auth/test

###
GET https://piana.ir:8443/api/ddd/sd
